modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
[[mods]]
modId="experiencebugfix"
version="${file.jarVersion}"
displayName="Experience Bug Fix"
displayURL="https://www.curseforge.com/minecraft/mc-mods/experience-bug-fix"
updateJSONURL="https://github.com/mactso/ExperienceBugFix/raw/main/update.json"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Experience Bug Fix.'
[[dependencies.experiencebugfix]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.experiencebugfix]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="SERVER"


